spring:
  datasource:
    url: ${DB_DEV_URL:${DB_LOCAL_URL:jdbc:postgresql://localhost:5432/resaporidb}}
    username: ${DB_DEV_USERNAME:${DB_LOCAL_USERNAME:postgres}}
    password: ${DB_DEV_PASSWORD:${DB_LOCAL_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 20000
